### ISSUE TITLE
handle stream errors

### ISSUE THREAD

**Issue by juliangruber** [tj/node-actorify#5]
maybe just forward

**Comment by tj** [comment]
i was going to just leave that out to delegate, since it's akin to req/res socket error handling that isn't message specific

**Comment by juliangruber** [comment]
You should probably mention that. When I see

``` js
a.pipe(b).pipe(a);
```

in docs it's obvious errors need to be handled, but with

``` js
b(a);
```

one might think you're not using former pattern because of error handling.

**Comment by tj** [comment]
yeah true good point. that's a big downside with node streams, kinda just a clusterfuck of unknowns haha

**Comment by juliangruber** [comment]
`a.pipe(b).pipe(a)` would be the idiomatic pattern but I agree that for non-stream-wizards this can be quite confusing and feel too flowy.

**Comment by juliangruber** [comment]
this is taken care of :)

**Comment by tj** [comment]
yeah that would be a little weird IMO, it uses a stream, it's not a stream haha

**Comment by juliangruber** [comment]
``` js
var actor = Actor();
con.pipe(actor.createStream()).pipe(con);
```

^ _that_ would be the idiomatic streams way :D Doesn't play nice with the name though

**Comment by tj** [comment]
yea that's awkward haha
